version: '3.5'

services:
  server:
    container_name: slack_clone_server
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - node_affiliate_postgres
    stdin_open: true
    tty: true
    networks:
      - slack_clone_net

  mongo:
    container_name: slack_clone_mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      - slack_clone_net

networks:
  slack_clone_net:
    name: slack_clone_net
